### ISSUE TITLE
batch uploads with internal folders? 

### ISSUE THREAD

**Issue by mekline** [CenterForOpenScience/osfr#100]
Hi there - thanks for making these issues available! I had a look at #99, but I think I have a more basic question (happy to have this deleted/merged if this doesn't belong here.)

I am successfully using basic osfr functions to upload & create components, directories, and files individually, but am not sure how to define a command that will upload all the files and subfolders of a local folder into an existing component (i.e. same as a "drag and drop" of an entire directory into the browser.) Is there a standard way to do this?

**Comment by aaronwolen** [comment]
Presently osfr does not support uploading multiple files or folders *but* it is being actively worked on. The first implementation might be limited to uploading the contents of a single folder (i.e., no recursion), but only as a stopgap. 

This question comes up quite a bit so I'll leave this issue open until it's actually resolved.

**Comment by aaronwolen** [comment]
This was addressed [v0.2.5](https://github.com/CenterForOpenScience/osfr/releases/tag/v0.2.5). Feel free to reopen if you have any other suggestions.
