### ISSUE TITLE
Feature request: Create dir with subdir's in one step

### ISSUE THREAD

**Issue by tiernanmartin** [CenterForOpenScience/osfr#101]
I thought I would be able to create a directory with subdirectories in a single `osf_mkdir()` call:

``` r
# note: before running this function the `data/` directory did not exist
osf_mkdir(proj, path = "data/data-raw")
```
but instead it duplicated the hierarchy like so:
![image](https://user-images.githubusercontent.com/8197328/57870575-3e0b5d80-77bc-11e9-96cf-c59eec6feb87.png)

I was able to get my intended result with the following code:
``` r
data_dir <- osf_mkdir(proj, path = "data")
osf_mkdir(data_dir, path = "data/raw-data")
```
... but it was not intuitive to me that I would have to first create the new directory and then create subdirectories.

Could `osf_mkdir()` be adapted to allow it to create a directory with subdirectories in a single call?

**Comment by aaronwolen** [comment]
`osf_mkdir()` does support creating subdirectories. This works for me with version 0.2.4:

```r
osf_create_project("Subdirectory Test") %>% 
  osf_mkdir("data/data-raw") %>% 
  osf_open()
```

![Screen Shot 2019-05-16 at 2 02 47 PM](https://user-images.githubusercontent.com/1067915/57879994-4cb93b00-77e3-11e9-9b56-dd3f0132a2cd.png)

Can you verify you're running the latest version and try the above example?

**Comment by tiernanmartin** [comment]
Installed v 0.2.4 and your reprex works.

Thanks!
