### ISSUE TITLE
Trouble modifying files

### ISSUE THREAD

**Issue by tiernanmartin** [CenterForOpenScience/osfr#102]
The need to pass a directory to `osf_upload()` when modifying a file is a bit cumbersome.

``` r
library(osfr)

datasets::iris %>% write.csv("iris.csv")

proj <- osf_create_project("Modify Test")

iris <- proj %>%  
  osf_upload("iris.csv")

# make a subset of iris 
datasets::iris[1:5,] %>% write.csv("iris.csv")

iris %>% 
  osf_upload("iris.csv", overwrite = TRUE)

#> Error: Uploading to an `osf_tbl_file` requires a directory
#> * `x` contains a file
```
When the file is located in the project's root directory it isn't too hard to figure out how to fix this:

``` r
proj %>% 
  osf_upload(path = "iris.csv", overwrite = TRUE)

# Succeeds
```
But it took me a while to figure out how this should work when the targeted file is located _within a subdirectory_. Eventually I found the following solution but it took some tinkering:

``` r
iris_subdir <- proj %>% 
  osf_mkdir("data/data-raw") %>% 
  osf_upload("iris.csv")

proj %>% 
  osfr::osf_ls_files(path = dirname("data/data-raw")) %>% # find the 'data/data-raw' subdirectory 
  osf_upload(path = "iris.csv", overwrite = TRUE)

# Succeeds

```
Why does `osf_upload()` need a directory instead of a file when modifying an existing file?

**Comment by aaronwolen** [comment]
Appreciate the detailed feedback!

I must admit, the error message you referenced is confusing and unhelpful. It's one of those things that totally made sense at the time I wrote it but seeing it now with fresh eyes I'm like 😖. I'll improve it in the next update. 

Just to be clear, `osf_upload()` can point to a directory, subdirectory _or_ a node (i.e., project or component) but `x` cannot point to an OSF file:

```r
write.csv(iris, "iris.csv")

iris_proj <- osf_create_project("Modify Test")
iris_dir   <- osf_mkdir(iris_proj, "data/data-raw")

# this is okay
iris_in_root <- osf_upload(iris_proj, "iris.csv")
# and this is okay 
iris_in_dir <- osf_upload(iris_dir, "iris.csv")
# but this is not and will trigger the error message in question
osf_upload(iris_in_root, "iris.csv", overwrite = TRUE)
```

I agree that overwriting a file on OSF by directly uploading to the file itself makes some intuitive sense. However, I decided against it for two reasons:

1. To be consistent with OSF's GUI, which only permits dragging and dropping to a root node or directory

    ![Screen capture demonstrating OSF only allows files to be uploaded to a project or a directory.](https://user-images.githubusercontent.com/1067915/57937019-bdfff900-788a-11e9-8add-44b5518c49d3.gif)
 
2. To prevent users from mistakenly overwriting a file on OSF with a totally different file's content. For example, something like this would be possible

    ```
    pdf("iris.pdf")
    plot(iris)
    dev.off()

    osf_upload(iris_in_root, "iris.pdf", overwrite = TRUE)
    ```

    The result would be a PDF file on OSF called `iris.csv`. No good.

**Comment by tiernanmartin** [comment]
That is a very clear explanation of the design choices. I find it really helpful to understand these sort of things when I'm learning to use software, and hopefully other users of this package will benefit from it too. Thanks for taking the time to walk through the explanation and create the GIF!

What is your recommended workflow for retrieving a subdirectory? In the example above you save `iris_dir` after running `osf_mkdir()`, but what is the best way of targeting an _existing_ subdirectory?

In my reprex I used a hack-y feeling approach: `osfr::osf_ls_files(x = proj, path = dirname("data/data-raw"))` -- is there a more straightforward way of retrieving a subdirectory's osf_tbl_file?

Thanks again!

**Comment by aaronwolen** [comment]
Glad it helped you out. BTW, if there's any part of the docs that you found confusing, PRs are very much appreciated!

You're right to use `osf_ls_files()` to retrieve an existing directory. The `type` argument let's you filter the results to include only folders:

```
osf_ls_files(osf_proj, type = "folder")
```

You can also use `pattern` if you know some or all of the directory's name. So if I was looking for the raw data directory located inside `data/` and I didn't remember exactly what it was called, I'd run:

``` r
osf_ls_files(osf_proj, path = "data", type = "folder", pattern = "raw")
```

**Comment by tiernanmartin** [comment]
The `pattern` parameter sounds useful.

Happy to submit a PR if I find any opportunities to clarify the docs.
