### ISSUE TITLE
duplicated progress bars

### ISSUE THREAD

**Issue by tpyork** [CenterForOpenScience/osfr#108]
When uploading individual files or directories i get duplicated progress bars. This is true whether uploading an individual file or an entire directory.

**Comment by tpyork** [comment]
# upload folder containing files
cr_project <- osf_retrieve_node("zy6nh")

cr_project %>% 
  osf_open()

osf_upload(cr_project, "data")
osf_upload(cr_project, "data", progress= TRUE)
osf_upload(cr_project, "data", conflicts= 'overwrite', progress= TRUE)
##strange behavior above where the progress bars are duplicated when overwriting during upload.

**Comment by aaronwolen** [comment]
Should be fixed in v0.2.6, which is currently on the `dev` branch. Thanks for reporting!
