### ISSUE TITLE
osf_ls_nodes converts "&" in folder name to "&amp;"

### ISSUE THREAD

**Issue by sTeamTraen** [CenterForOpenScience/osfr#117]
If a component of a project contains an "&" character in its name, osf_ls_nodes() returns that name with "&" converted to "&amp;". 

Minimum reprex code:

library(osfr)
mynode <- osf_retrieve_node("8ztfw")
folders <- osf_ls_nodes(mynode, n_max=Inf)
print(folders$name)

**Comment by aaronwolen** [comment]
Thanks for reporting. The conversion to HTML entity names happens server-side but I agree we should convert them back to the original symbols.

**Comment by aaronwolen** [comment]
This is fixed in the next version.

**Comment by sTeamTraen** [comment]
Hooray! :-))
