### ISSUE TITLE
Trawl outside of OSF storage

### ISSUE THREAD

**Issue by chartgerink** [CenterForOpenScience/osfr#37]
Currently, the `get_files_info()` and `clone_project` functions only operate on OSF storage and not on the other add-ons. As a result, users get incomplete results, which might be very confusing. 

Index of functions that require updating (being updated based on discussion):
1. `get_files_info`
2. `clone_project`

**Comment by jcolomb** [comment]
I think download_files has the same issue.

**Comment by csoderberg** [comment]
Closing this issue out, as we're about to pull in a completely revamped version fo the package, which doesn't have a clone_project feature and different names for the other features. This ticket is still conceptually relevant though, so I'll create a new feature request once the new version is merged in.
