### ISSUE TITLE
MVP to-do list

### ISSUE THREAD

**Issue by chartgerink** [CenterForOpenScience/osfr#50]
I keep track of all the things I still need to complete, and I always lose my scratchpads :spiral_notepad: so sharing all these notes here. Woo for chaos :fire: 

__Please note all changes are currently being made on the `mvp` branch (so any PRs relating to these, please on that branch)__

| Old name | New name |
| ------------- | -------------- |
| `login` | `auth` |
| `upload_new` | `upload_new_files` |
| `upload_revision` | `upload_revised_files` | 

| Function | Updated | Tested | Unit tests | Docs |
| - | - | - | - | - |
| `get_config` | :heavy_check_mark: | | | :heavy_check_mark: |
| `construct_link` | :heavy_check_mark: | | | :heavy_check_mark: |
| `process_type` | :heavy_check_mark: | | | :heavy_check_mark: |
| `process_json` | :heavy_check_mark: |  | | :heavy_check_mark: |
| `process_category` | :heavy_check_mark: |  | | :heavy_check_mark: |
| `get_config` | :heavy_check_mark: |  | | :heavy_check_mark: |
| `is_valid_osf_id` | :heavy_check_mark: |  | | :heavy_check_mark: |
| `pre_slash` |  |  | |  |
| `rm_space` | | | |  |
| `upload_new_files` | :heavy_check_mark: |  | | :heavy_check_mark: |
| `upload_revised_files` | :heavy_check_mark: | | | :heavy_check_mark: |
| `upload_files` | :heavy_check_mark: | | | :heavy_check_mark:  |
| `download_files` | :heavy_check_mark:  |  | | :heavy_check_mark: |

# Design principles

* Make functions operate as if user is logged in or not (don't make them specify private/public arguments)

**Comment by huifenzhou** [comment]
Two days ago, the login function worked well. 
Yesterday, I used the login function to connect R and OSF, but it didn't work. Then I use auth function, however, there is no this kind of function. Do you know how to fix this problem.

**Comment by chartgerink** [comment]
@huifenzhou please post a separate issue with a more detailed description of errors if you'd like assistance.

This issue is specifically for developing on the `mvp` branch and I'd like to not mix it with separate issues. This is also why the `auth` function is not available to you, because you installed from the `master` branch

**Comment by csoderberg** [comment]
Closing this issue out, as we're about to pull in a completely revamped version fo the package and the mvp branch as been merged into master as is in preparation for the new stable code.
