### ISSUE TITLE
Moving Unopened Files Between Components

### ISSUE THREAD

**Issue by McKayMDavis** [CenterForOpenScience/osfr#56]
I am trying to automate moving files that I have uploaded with a Shiny app from one component to another in OSF. Turns out a file has no ID until it is viewed in OSF--a huge problem if you have many files and don't want to go clicking through all of them. As far as I have seen in the files and functions of osfr, there is no way to access the files unless they have an ID. I understand that the file is hosted with the waterbutler API. Is there any way with this package or otherwise to move files between components without needing a file ID? Maybe directly through one of the waterbutler links returned from Django info?

**Comment by bgrich** [comment]
Unfortunately, I don't think there is a way to do this directly with `osfr` at the moment. However, the `osfr::get_files_info()` function should return a WaterButler link for all of the files and folders in the provided project id. You could use the links returned by `get_files_info()` to move each file without having to view the file on OSF first. The details on moving files with a WaterButler link are [given here](https://waterbutler.readthedocs.io/en/latest/api.html#v1-api).  

If your files are in a folder, you should be able to move the folder with all the files. The folder WaterButler links are also pulled down via `get_files_info()`.

**Comment by McKayMDavis** [comment]
@bgrich Thank you for the reply. I've viewed this link previously. Is there a package you would recommend I use to issue the request? I've looked into `httr` with no luck, but perhaps I simply don't understand what it's doing. Also, I have found a couple of bugs in the package, which I have mostly changed on a forked repo. Should I add these in separate issues, or just include them here?

**Comment by McKayMDavis** [comment]
@bgrich I just solved my first question. The second one still stands.

**Comment by bgrich** [comment]
Great! For any other bug I think separate issues will make it easier to track them. Also, some of the bugs may have already been addressed or are currently being addressed in the `mvp` branch (where current development is happening).

**Comment by McKayMDavis** [comment]
Great! I will check that out. I'm so glad this package has been turned over to OSF and can get some TLC.

**Comment by McKayMDavis** [comment]
Sorry, one more question. Is there any plan going forward to incorporate functions that work directly with WaterButler so that a file id is not necessary? This would go a long way for building automation scripts to interact with OSF.

**Comment by bgrich** [comment]
There isn't a plan to write functions that directly interface with WaterButler in the current version of the package, but it is definitely a possibility for later versions. Creating more options for automating working with files would be great. If you have any suggestions for specific features, please feel free to submit or post them.

**Comment by McKayMDavis** [comment]
I have a couple. The ones I have solved are: interacting with files within folders contained in a component without needing file id's, recursively obtaining a directory (similar to the one returned by `get_nodes`) of all nodes and files and their nodes and files etc. within a project.

**Comment by aaronwolen** [comment]
Closing this issue now that it's possible to move unopened files between components. Here's a quick repex:

``` r
library(osfr)
proj <- osf_create_project("File Move Test")

comp1 <- osf_create_component(proj, "Component 1")
comp2 <- osf_create_component(proj, "Component 2")

write.csv(iris, "iris.csv")
iris_file <- osf_upload(comp1, "iris.csv")
osf_ls_files(comp1)
#> # A tibble: 1 x 3
#>   name     id                       meta            
#>   <chr>    <chr>                    <list>          
#> 1 iris.csv 5ded6906a30cf10009081d62 <named list [3]>

iris_file <- osf_mv(iris_file, to = comp2)
osf_ls_files(comp2)
#> # A tibble: 1 x 3
#>   name     id                       meta            
#>   <chr>    <chr>                    <list>          
#> 1 iris.csv 5ded6906a30cf10009081d62 <named list [3]>
```

<sup>Created on 2019-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
