### ISSUE TITLE
installation of mvp failed

### ISSUE THREAD

**Issue by jcolomb** [CenterForOpenScience/osfr#61]
I used: devtools::install_github('CenterForOpenScience/osfr', ref="mvp")
 and get

> ** testing if installed package can be loaded
> Error: package or namespace load failed for ‘osfr’ in namespaceExport(ns, exports):
>  undefined exports: welcome
> Error: loading failed
> Execution halted
> ERROR: loading failed

**Comment by bgrich** [comment]
Thanks for comment! I just merged some changes in PR #62 that should fix this installation problem. If there are still problems with the installation of the `mvp` branch, please let me know!
