### ISSUE TITLE
upload_files() not uploading revisions

### ISSUE THREAD

**Issue by davidrast3** [CenterForOpenScience/osfr#73]
When I use upload_files() to upload a new file to OSF it works. However, when I run upload_files() to upload revisions to those files, I cannot. Here is the code I am running along with the errors:

> upload_files(id   = 'https://osf.io/XXX, path = 'my_data.csv')
Error in upload_files(id = "https://osf.io/XXX", path = "my_data.csv") : 
  Something odd happened.

          If the problem persists, consider issuing a bug report on
          github.com/chartgerink/osfr

> upload_files(id   = 'XXX', path = 'my_data.csv')
Revising file...
Error in upload_revision(id, path, dest) : unused argument (dest)

**Comment by csoderberg** [comment]
thanks @davidrast3 for reporting this. The package is currently going through some major overhauls and the master branch is pretty far behind the mvp branch where we're making the changes. If you download the package from that branch, I think that should fix this problem (but please let us know if you're still experiencing problems). Once we have all the changes made we'll merge the mvp back into master. As a heads up, we'll likely be changing over many of the file names in the coming months to have them meet current best practices to move the package towards being CRAN ready and to have a stable initial version.

**Comment by davidrast3** [comment]
I've been using the mvp branch. Uploading a revised file works fine. However, uploading a new file to OSF does not work. When uploading a new file to OSF, I receive an error about an 'idx' object not found. If a file already exists in the project or component, then 'upload_files()' seems to work as expected. But in a new created (empty) project or component, 'upload_files()' results in the "object 'idx' not found" error.

Here is example code: 

`
remotes::install_github('chartgerink/osfr', ref = "mvp")
library(osfr)

upload_files(id = "12345",  path = "test.pdf")
Error in upload_files(id = "12345", "test.pdf") : object 'idx' not found
`

**Comment by csoderberg** [comment]
This is relevant to the 0.1.1 release. The code has changed in the current version (0.2.0) and uploading and updating files should now work.
