### ISSUE TITLE
import data into R without downloading first?

### ISSUE THREAD

**Issue by davidrast3** [CenterForOpenScience/osfr#74]
Is it possible to import data into R without first downloading it from OSF? Right now I can use download_files() to download a specific file from OSF but it would nice if we could import the data file directly without downloading.

For example, I currently run code like "rio::import(download_files(id='XXX', private=TRUE))" to import a datafile. Is it possible to have a command like "import_data()" that does this automatically?

**Comment by csoderberg** [comment]
@davidrast3 thanks for the suggestion! We have a base list of features that we're incorporating for the first version of the package that we're working on getting CRAN ready, but once version 1 is finalized we're hoping to iteratively add community feature request.

**Comment by aaronwolen** [comment]
The difficulty is any type of file can be uploaded to OSF. I think the approach you describe is the best strategy: use osfr to download files of interest and then use an appropriate data importing package (like rio) to read in the data.
