### ISSUE TITLE
osf_tbl function adds columned named metadata rather than meta

### ISSUE THREAD

**Issue by machow** [CenterForOpenScience/osfr#88]
I'm not sure if this is used somewhere else in the package. Normally the osf_tbl object uses a column named `meta`. However, in the code below it appears that there is a column named `metadata` instead. (This seems to happen when using osf_ls_node when there are no more subcomponents - it returns an empty osf_tbl with a metadata column).

https://github.com/CenterForOpenScience/osfr/blob/231919427f56a959a26a9201f3a8cbda8326e4e5/R/osf_tbl.R#L51

**Comment by aaronwolen** [comment]
Wow, good find. Thanks for for reporting!

**Comment by machow** [comment]
Thanks for the quick fix!
