### ISSUE TITLE
Unable to retrieve all files from an OSF component

### ISSUE THREAD

**Issue by lnalborczyk** [CenterForOpenScience/osfr#98]
Hi, let me first thank you for developing and maintaining this package, it's super useful.

I have an issue with downloading files from a subcomponent on OSF (which can be accessed there: https://osf.io/fjkhr/).

I'd like to access the .csv files present in this component (and to download them). Here is the code I use to first list these files:

```
# retrieve OSF data
osf_data <-
    # retrieve the OSF (main) project
    osf_retrieve_node("mwtvk") %>%
    # list components
    osf_ls_nodes() %>%
    # retrieve the component containing the data
    filter(name == "data_emo_stroop_xp") %>%
    # list files in this repository
    osf_ls_files() %>%
    # filter .csv files
    filter(str_detect(name, ".csv$") )
```

However, the `osfr` package seems to only "see" *some* of the .csv files, and not all of them. As can be seen on OSF, there are currently 13 .csv files in this component, but for some reason `osfr` "sees" only four of them...

Would you have any idea about the problem here ?

Thanks ! 

Ladislas

**Comment by csoderberg** [comment]
Hi Ladislas,

I think I know what is causing the problem. The osf_ls_files() function has an n_max argument, which specified the maximum number of files that should be returned. By default n_max is set to 10. So, only the first 10 files in the data_emo_stroop_xp component are being returned, and then the filtering is being done on those 10 returned file. If you increase the n_max number then you should be able to see all the csv files after filtering.

**Comment by aaronwolen** [comment]
This has tripped up a number of users. I'm considering increasing `n_max`'s default or possibly informing users when the number of returned results is less than the total number of project files. 

BTW, you can use the `pattern` argument to perform the filtering server-side:

```
osf_retrieve_node("fjkhr") %>%
  osf_ls_files(pattern = "csv", n_max = Inf)
```

**Comment by lnalborczyk** [comment]
Thank you for your prompt answers, it solved it ! I just have another short question. I am downloading a batch of .csv files with the following command (where `osf_data` is the results of the code in my previous message):

```
    osf_data %>%
        # for each line (each csv file), download it
        {split(., 1:nrow(.) )} %>% lapply(osf_download, overwrite = TRUE)
```

I would like to save these downloaded files not in the current directory, but in a subdirectory called "data" (for instance). I have tried to use the `path` argument, but it only serves to specify the name of the file locally, not to define a folder in which the downloaded files should be saved... or I am using it wrong ? I have used `path = "./data/"` but it gives the following error:

```
Error in curl::curl_fetch_disk(x$url$url, x$disk, handle = x$url$handle) : 
  Failed to open file XXXX/data.
```

Any idea ?

**Comment by aaronwolen** [comment]
You need to specify the full filepath (i.e., it must include the subdirectory and the file name). Look out for a more convenient interface for downloading multiple files in an upcoming release.

**Comment by lnalborczyk** [comment]
Thank you for your answer. My problem was that I did not know how to specify the file name, given that it varies within the lapply call. But the following code worked for me:

```
    osf_data %>%
        # for each line (each csv file)
        {split(., 1:nrow(.) )} %>%
        # download it and put it in the "data" folder
        lapply(osf_download, path = paste("data/", .$name), overwrite = TRUE)
```

Thank you again !

**Comment by aaronwolen** [comment]
Multi-file download/upload functionality was added in [v0.2.5](https://github.com/CenterForOpenScience/osfr/releases/tag/v0.2.5).
